### ISSUE TITLE
[Feature Request] Allow for an ignore tag

### ISSUE THREAD

**Issue by gajewsk2** [HelenFoster/KanjiVocab#10]
The current behavior completely overwrites the KanjiVocab fields. I think it would be useful to allow users to ignore cards that have a tag (KanjiVocabIgnore) to indicate that the tagged cards shouldn't be (force) updated. 

This way if the user decides to make manual alterations to the readings or words their work would not be lost on re-runs.

**Comment by HelenFoster** [comment]
I suspect most users would have difficulty remembering to add the tag, which leads to a lot more frustration than just having to use a different field.

**Comment by HelenFoster** [comment]
That sort of workflow also removes the option of auto-updating the edited cards later, when someone's vocab situation has moved on.

**Comment by gajewsk2** [comment]
I guess just using an extra field would work too. I'm basing this style off of morphman though, which allows you to look at notes without editing them and thought that style seems reasonable.

Without something like this, you'll have to do some fancier template logic, and it seems reasonable to ask the program to not edit a subset of your cards - which you could then find easily via tag to update when or if you decide to move it back to the automated flow.

EDIT: Running into this now. So it wouldn't just be a single field to update in my case, as I would want at least my questions and answers to match, so at least two manually maintained additional fields, and I would need to know when to ignore the automatically generated ones.

I've seen 禽獣 in the wild, but it's the last word on my card for 禽. I'd like to put it at the front, and keep it that way from now on.

**Comment by HelenFoster** [comment]
I'm coming around to the idea. Maybe KanjiVocabFreeze.
