### ISSUE TITLE
Field names for results?

### ISSUE THREAD

**Issue by HelenFoster** [HelenFoster/KanjiVocab#11]
So, spaces in field names are actually a bit of a pain. @gajewsk2 I think you might have been right about this! On the other hand, renaming them could annoy existing users. Should I do it?

**Comment by gajewsk2** [comment]
I think in order to enable a better experience for future users a rename would be well in order. A anki2.1 json add-on config would probably allow existing users to switch back without too much of a hassle though.

**Comment by HelenFoster** [comment]
I don't really want config in a third place. And it's not hard to rename fields (and some people might be glad to do it) so maybe not really a problem.
