### ISSUE TITLE
Please, Anki 2.1 support.

### ISSUE THREAD

**Issue by JulyMorning** [HelenFoster/KanjiVocab#7]
thanks :3

**Comment by HelenFoster** [comment]
Now that 2.1 is properly out, it would be good for all the addons to be updated, but I'm not sure when I'll be getting to this one.

**Comment by JulyMorning** [comment]
It's one of the crucials – at least, for me, but I guess for many who study kanji. Won't go for 2.1 until this addon have its support :(

**Comment by HelenFoster** [comment]
I'm planning to start work on it soon.

**Comment by JulyMorning** [comment]
it would be awesome, thanks

**Comment by gajewsk2** [comment]
Any progress on this? really looking forward to using with 2.1

**Comment by HelenFoster** [comment]
I'd like to test it a good bit more before releasing on AnkiWeb, but it might be sorted!

**Comment by gajewsk2** [comment]
2.1 seems to be working for me. Side question, does this hard overwrite previous questions, everytime it runs?

**Comment by HelenFoster** [comment]
Thanks for letting me know. Yes, it overwrites the questions every run, so it's best not to edit them, and put any custom keywords into a different field.

**Comment by HelenFoster** [comment]
Released on AnkiWeb today.
