### ISSUE TITLE
Some Kanji aren't generating relevant words

### ISSUE THREAD

**Issue by gajewsk2** [HelenFoster/KanjiVocab#8]
I'm really confused why ~800 of my ~3700 kanji cards aren't getting vocab words generated, despite being relavant. Here's a few examples. A lot of them are quite common.

1
KanjiVocab cards
Kanji: 初

Scanned Fields:
Note Type: Japanese
Vocab: 最初

2
KanjiVocab cards
Kanji: 凹

Scanned Fields:
Note Type: Japanese
Vocab: 凹凸

![image](https://user-images.githubusercontent.com/4039913/56546961-875fe880-6541-11e9-9f34-ac4880a552ae.png)
```
Loaded config file
Wrote config file
Found vocab question field
Found vocab response field
Found vocab extra field
Loaded dictionary
Done vocab scan on note type "Japanese" (fields "Vocab", "VocabReading")
 Marked 231 known words from 6223 active notes
 (72 duplicates, 103 with >1 possible word, 3814 not found)
Done text scan on note type "Japanese" (field "Expression")
 Marked 3802 known words from 6223 active notes
 (21646 duplicates, 21404 with >1 possible word, 8142 not found)
Done text scan on note type "Japanese Grammar" (field "Expression")
 Marked 147 known words from 399 active notes
 (2706 duplicates, 2549 with >1 possible word, 1899 not found)
Done text scan on note type "Japanese Text Input" (field "Expression")
 Marked 8 known words from 316 active notes
 (978 duplicates, 1090 with >1 possible word, 583 not found)
Created questions
Updated 3772 kanji notes (1521 having known word(s))
Finished
```
I'd like to give all my 常用漢字 a keyword, any ideas to help accomplish that?

**Comment by HelenFoster** [comment]
Could you show me the field contents of a few cards that you think should be providing the missing words?

I'm suspicious about the "3814 not found" during the vocab scan.

<s>Also in a vocab scan, I think the numbers normally add up to the number of active notes, and yours don't.</s> - looks like they add up for me because I have a non-repeating vocab deck. Do your Vocab/VocabReading have a fair number of duplicates?

On the other hand, 最初 is nf01 so should appear whether it's getting picked up from any of your decks or not. I am getting `最〇[さいしょ]` in my results.

**Comment by HelenFoster** [comment]
Also, can you make sure your 初 doesn't have any extra HTML or something hiding in it?

**Comment by gajewsk2** [comment]
> Could you show me the field contents of a few cards that you think should be providing the missing words?
> 
> I'm suspicious about the "3814 not found" during the vocab scan.
> 
> Also in a vocab scan, I think the numbers normally add up to the number of active notes, and yours don't. - looks like they add up for me because I have a non-repeating vocab deck. Do your Vocab/VocabReading have a fair number of duplicates?
> 
> On the other hand, 最初 is nf01 so should appear whether it's getting picked up from any of your decks or not. I am getting `最〇[さいしょ]` in my results.

Oh yes, I have many duplicates for Vocab, but Expressions _tend_ to be unique. I use a lot of shared decks though for sentence mining, and don't curate them for uniqueness though. My collection is around 200k cards. XD

Good thought on the html question, though I confirmed there are cards without html in them, (besides b tags, actually generated by your other plugin :))

I've attached a sample of my kanji card, and my sentence mined cards for this particular kanji. I'll keep digging on my end, thanks for all the help with this.
[kanjivocab.zip](https://github.com/HelenFoster/KanjiVocab/files/3121421/kanjivocab.zip)

**Comment by HelenFoster** [comment]
I meant that HTML hiding in the kanji field would prevent getting any results. As I suspected, your sample RTK card has Kanji = `<div>初</div>` . Maybe my code should filter out HTML from kanji and vocab fields.

The other problem is that it's not handling furigana in the vocab reading field. Since Anki's Japanese Support says "reading" to mean "furigana", that's actually pretty bad. In the meantime, you can try unselecting the reading in the scan options, and just using the vocab expression by itself.

**Comment by HelenFoster** [comment]
Regarding HTML, let's try this for now: acf760d

I decided to clean all the input fields. For text scanning, there's a slight trade-off, but it won't make a difference in most cases.

**Comment by gajewsk2** [comment]
Per the new code:
```
Loaded config file
Wrote config file
Found vocab question field
Found vocab response field
Found vocab extra field
Loaded dictionary
Done vocab scan on note type "Japanese" (fields "Vocab", "VocabReading")
 Marked 232 known words from 6245 active notes
 (71 duplicates, 104 with >1 possible word, 3831 not found)
Done text scan on note type "Japanese" (field "Expression")
 Marked 3820 known words from 6245 active notes
 (21732 duplicates, 21481 with >1 possible word, 8171 not found)
Done text scan on note type "Japanese Grammar" (field "Expression")
 Marked 147 known words from 399 active notes
 (2706 duplicates, 2549 with >1 possible word, 1899 not found)
Done text scan on note type "Japanese Text Input" (field "Expression")
 Marked 8 known words from 316 active notes
 (978 duplicates, 1090 with >1 possible word, 583 not found)
Created questions
Updated 3772 kanji notes (1527 having known word(s))
Finished

```

So that gave me 13 more cards, yay!

I guess I didn't understand that the card needs to be "active" to show unless it's in the dictionary list? That explains 凹, which I don't have any vocab cards "active" of despite them existing. I think it'd be nice to allow "unknown" ones in the extra field potentially.


> The other problem is that it's not handling furigana in the vocab reading field. Since Anki's Japanese Support says "reading" to mean "furigana", that's actually pretty bad. In the meantime, you can try unselecting the reading in the scan options, and just using the vocab expression by itself.

Had a few questions on this:
1. By vocab expression, you're meaning the Expression field right? 
2. And what's the intention of your "reading" field, to be a pure reading （さいしょ, instead of furigana'd)?
3. What's the intention of this feature?

If I run it without the 1st note type, that I had picture above, I get:
```
Loaded config file
Wrote config file
Found vocab question field
Found vocab response field
Found vocab extra field
Loaded dictionary
Done text scan on note type "Japanese" (field "Expression")
 Marked 4029 known words from 6245 active notes
 (21523 duplicates, 21481 with >1 possible word, 8171 not found)
Done text scan on note type "Japanese Grammar" (field "Expression")
 Marked 147 known words from 399 active notes
 (2706 duplicates, 2549 with >1 possible word, 1899 not found)
Done text scan on note type "Japanese Text Input" (field "Expression")
 Marked 8 known words from 316 active notes
 (978 duplicates, 1090 with >1 possible word, 583 not found)
Created questions
Updated 3772 kanji notes (1525 having known word(s))
Finished

```

**Comment by HelenFoster** [comment]
In a vocab scan, the reading field is optional, so you can do: Note type = Japanese; Scan type = vocab; Expression field = Vocab; Reading field blank.

As you say, the "reading" field only looks for a pure reading like さいしょ . This isn't good.

The intention is to help it pinpoint which word is known, if the expression has multiple readings. If expression X has readings Y and Z, and you know it with reading Y, it won't be useful to get kanji questions asking what's the kanji for Z?

> I guess I didn't understand that the card needs to be "active" to show unless it's in the dictionary list? That explains 凹, which I don't have any vocab cards "active" of despite them existing. I think it'd be nice to allow "unknown" ones in the extra field potentially.

Right, it could be useful to adjust what sort of "unknown" words are allowed. But I want to be careful not to make the options too complicated.

**Comment by gajewsk2** [comment]
Ah, makes sense.
I've been using this in combination with Bulk-RtK keyword so every cards
kanji has other words that use the kanji. For a reason like this, as well,
it would be useful to show other unknowns, just like the ambiguous ones
now, like this:
https://twitter.com/kanjieater/status/1119422260538900482?s=20

I think an ideal experience would be something like an additional checkbox
(like the allow ambiguous one),something to the effect of allow unknown.
Then it could pick up any word, even if it's not active yet.

**Comment by HelenFoster** [comment]
Are you particularly looking for the words in your library of unstudied cards, or could they be anything?

I was thinking there could be an adjuster for how easily to take unknown words from the dictionary. See "Word Priority Marking" in http://edrdg.org/jmdict/edict_doc.html#IREF05

**Comment by gajewsk2** [comment]
I'd be fine with either and thinks there's a place for both actually. I'd just like to see other words that use the same Kanji, than not see anything at all.

Thanks for the link, I'll check it out.

**Comment by HelenFoster** [comment]
Right, both could have uses. A partially-curated collection of unlearned cards is likely to be more relevant to a user's interests than dictionary ratings. But a lot of people won't have that, so then the dictionary info is needed.

> I think it'd be nice to allow "unknown" ones in the extra field potentially.

Is it important to be able to choose differently for "extra"? The algorithm would still prioritise actual known words, and those would still be highlighted as they are now.

**Comment by gajewsk2** [comment]
I don't think so, extra is really just the backup, so not being able to
distinguish seems like a fine way to start, since it falls under the
"unknown" bucket technically which already exists.

2019年4月28日(日) 6:08 HelenFoster <notifications@github.com>:

**Comment by HelenFoster** [comment]
For scanning unknowns, I'm thinking about adding checkboxes on the "Cards to scan" page, since it's really a scan option.

By the way, your email replies seem to be leaking your unsubscribe link, so if anyone (or even a bot) clicks on it, you might not get notified about this thread any more.

**Comment by gajewsk2** [comment]
Ok, yeah that makes a lot of sense and should be an intuitive location for
the checkbox.

Thanks for the warning, didn't realize that it was posting all of that.
I'll try to disable it, but I just confirmed you have to be logged in to
unsubscribe.

**Comment by MrPiethon** [comment]
> 
> 
> > Could you show me the field contents of a few cards that you think should be providing the missing words?
> > I'm suspicious about the "3814 not found" during the vocab scan.
> > Also in a vocab scan, I think the numbers normally add up to the number of active notes, and yours don't. - looks like they add up for me because I have a non-repeating vocab deck. Do your Vocab/VocabReading have a fair number of duplicates?
> > On the other hand, 最初 is nf01 so should appear whether it's getting picked up from any of your decks or not. I am getting `最〇[さいしょ]` in my results.
> 
> Oh yes, I have many duplicates for Vocab, but Expressions _tend_ to be unique. I use a lot of shared decks though for sentence mining, and don't curate them for uniqueness though. My collection is around 200k cards. XD
> 
> Good thought on the html question, though I confirmed there are cards without html in them, (besides b tags, actually generated by your other plugin :))
> 
> I've attached a sample of my kanji card, and my sentence mined cards for this particular kanji. I'll keep digging on my end, thanks for all the help with this.
> [kanjivocab.zip](https://github.com/HelenFoster/KanjiVocab/files/3121421/kanjivocab.zip)

May I suggest taking the duplicate vocabulary words and combining the sentences? This way you can see the keyword being used in multiple sentences. 200,000 flashcards is pretty intense, and I worry that there will be countless cards that you will never see (if you keep adding newly mined sentences). Or perhaps maybe sort the cards by most common occurrence.

**Comment by gajewsk2** [comment]
> > > Could you show me the field contents of a few cards that you think should be providing the missing words?
> > > I'm suspicious about the "3814 not found" during the vocab scan.
> > > Also in a vocab scan, I think the numbers normally add up to the number of active notes, and yours don't. - looks like they add up for me because I have a non-repeating vocab deck. Do your Vocab/VocabReading have a fair number of duplicates?
> > > On the other hand, 最初 is nf01 so should appear whether it's getting picked up from any of your decks or not. I am getting `最〇[さいしょ]` in my results.
> > 
> > 
> > Oh yes, I have many duplicates for Vocab, but Expressions _tend_ to be unique. I use a lot of shared decks though for sentence mining, and don't curate them for uniqueness though. My collection is around 200k cards. XD
> > Good thought on the html question, though I confirmed there are cards without html in them, (besides b tags, actually generated by your other plugin :))
> > I've attached a sample of my kanji card, and my sentence mined cards for this particular kanji. I'll keep digging on my end, thanks for all the help with this.
> > [kanjivocab.zip](https://github.com/HelenFoster/KanjiVocab/files/3121421/kanjivocab.zip)
> 
> May I suggest taking the duplicate vocabulary words and combining the sentences? This way you can see the keyword being used in multiple sentences. 200,000 flashcards is pretty intense, and I worry that there will be countless cards that you will never see (if you keep adding newly mined sentences). Or perhaps maybe sort the cards by most common occurrence.

I quite like my current workflow of using my anki decks as a sentence bank, and finding cards that are i+1 via morphman. Having a large set allows me to have a great selection of high quality content that's only a keypress away from integrating into my next days studies. It's fantastic. 

It's ok to have cards I will never see, as the intent is to provide options with a variety of uses for as many words as possible. I study by sentence primarily on the front, with the back highlighting the Focus'd Vocab (shoutout to HelenFoster's JSH addon). Morphman already accomplishes the sorting you've mentioned.

I think we've strayed a bit off topic though, but i hope that answers your concern :)

**Comment by gajewsk2** [comment]
Found another one, that I'm hoping you can clarify the behavior on. No html in this one and I'm using your latest version. (again, I do have my fields modiefied without spaces, Kanji Vocab Extra = KanjiVocabExtra)

I know you mentioned the nf01 was relevant for the other kanji, does ichi1 not get picked up for some reason?

君	きみ	ichi1

[kanjivocab.zip](https://github.com/HelenFoster/KanjiVocab/files/3143955/kanjivocab.zip)

**Comment by HelenFoster** [comment]
Currently, ichi1 isn't used for that.

Next, I'm planning to do something about the furigana, and the dictionary words option which doesn't look at your cards (for which ichi1 is relevant). The unknown cards option needs more thought.

**Comment by gajewsk2** [comment]
> Currently, ichi1 isn't used for that.
> 
> Next, I'm planning to do something about the furigana, and the dictionary words option which doesn't look at your cards (for which ichi1 is relevant). The unknown cards option needs more thought.

In the attached deck, I have words that i've already encountered that use 君 though and they aren't getting picked up. Any insight on why that would be?

**Comment by HelenFoster** [comment]
> In the attached deck, I have words that i've already encountered that use 君 though and they aren't getting picked up. Any insight on why that would be?

Looks like the attached is all unknown cards, and I haven't done that yet either.

**Comment by HelenFoster** [comment]
I've done the the furigana and the dictionary words option.

**Comment by HelenFoster** [comment]
And here is the option for the unknown cards too.

**Comment by gajewsk2** [comment]
This is fantastic. I went from having 400~ without vocab to only 26. A few follow-ups:

1. I've got an example here of where I think a vocab word exists and a kanji should be matching it. Any idea why it's not?
[kanjivocab.zip](https://github.com/HelenFoster/KanjiVocab/files/3169323/kanjivocab.zip)


2. Would it be possible to order the inactive cards by frequency or due date?

**Comment by HelenFoster** [comment]
I just renamed the new config key, so on the first run after updating, it will forget how the new checkboxes were set. I didn't think that was serious at this stage, but just so you're not surprised.

> I've got an example here of where I think a vocab word exists and a kanji should be matching it. Any idea why it's not?

One of them isn't in the dictionary, and for the others it can't tell which reading is the right one. In the vocab scan, if you re-enable the reading field, you should get 曾祖父 in "extra".

> Would it be possible to order the inactive cards by frequency or due date?

So you're getting too many words for some kanji, and want it to pick differently?

**Comment by gajewsk2** [comment]
> 
> > I've got an example here of where I think a vocab word exists and a kanji should be matching it. Any idea why it's not?
> 
> One of them isn't in the dictionary, and for the others it can't tell which reading is the right one. In the vocab scan, if you re-enable the reading field, you should get 曾祖父 in "extra".
> 
![image](https://user-images.githubusercontent.com/4039913/57574058-9676df80-73f7-11e9-85a2-c45345a5c3e5.png)
Right, I expected 曾祖父  to show up on the KanjiVocabQuestion card. I do have my reading field enabled (pictured), however it still is not showing on the Kanji card with 曾. Am I missing something?

> > Would it be possible to order the inactive cards by frequency or due date?
> 
> So you're getting too many words for some kanji, and want it to pick differently?

Yeah. Though I think I get the reason why. For 君, I guess since it's ambiguous it goes to the KanjiVocabExtra field. While these less common words are in the Question field. 
君臨[くんりん]　 諸君[しょくん]　 君主[くんしゅ]　 暴君[ぼうくん]

Ordering them by frequency would still makes sense I think. 


EDIT: Well, I just realized I didn't have the dictionary set to `all`. Re-running now, so I'll update this with anything that changes, though I honestly don't know what to expect from the updated dictionary. Do you weight dictionary entries over card entries? Or just strip furigana, and look up the reading from the dictionary table?

**Comment by gajewsk2** [comment]
Running with the dictionary set to all fills in all of my jyouyou kanji. I'm thrilled!

**Comment by gajewsk2** [comment]
I'll open a new issue for the frequency based sorting

**Comment by HelenFoster** [comment]
As far as the dictionary knows, 〇祖父[そうそふ] could equally well be 曾 or 曽.

〇[きみ] should be coming up as "likely". Looks like it's just not ranked as common in news.

>Do you weight dictionary entries over card entries?

Card entries have more weight.
